# Generated by Django 3.2.8 on 2021-10-12 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='headind',
            new_name='heading',
        ),
    ]
